services:
  - type: web
    name: tlfq-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://invertis-feedback-system-6s1e.onrender.com/
    autoDeploy: true
