services:
  - type: static
    name: tlfq-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://invertis-feedback-system-6s1e.onrender.com/
    autoDeploy: true
